# Generated by Django 3.1.6 on 2021-02-06 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationInstitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('isVerified', models.BooleanField(default=False, null=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'No Formal Education'), (1, 'Primary/Elementary Education'), (2, 'Secondary/High School Education'), (3, '10th Grade'), (4, '12th Grade'), (5, 'Graduate'), (6, 'Post Graduate'), (7, 'Doctorate')], default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.educationinstitution')),
            ],
            options={
                'verbose_name': 'Education Institution',
                'verbose_name_plural': 'Education Institutions',
                'db_table': 'education_institution',
            },
        ),
    ]
