# Generated by Django 3.1.6 on 2021-02-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_educationinstitution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationinstitution',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Unknown'), (1, 'School'), (2, 'College'), (3, 'University')], default=0),
        ),
    ]
