# Generated by Django 3.1.6 on 2021-02-06 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210206_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='educationInstitution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.educationinstitution'),
        ),
    ]
